#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

path="$(dirname "$0")/bootstrap"
$path

echo "==> Setting up DB…"
# reset database to a fresh state.
bin/rake db:create 
bin/rake db:reset

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  echo "==> Installing or updating Foreman gem…"
  gem install foreman
  true
fi

echo "==> App is now ready to go!"
