brew "imagemagick", args: ['with-ghostscript']
brew "composer"
brew "mysql", restart_service: :changed
brew "nginx", restart_service: :changed
brew "rbenv"
brew "phpenv"
brew "nodenv"
brew "yarn", args: ['without-node']
