brew "imagemagick", args: ['with-ghostscript']
brew "composer"
brew "mysql@5.7", restart_service: :changed
brew "nginx", restart_service: :changed
brew "rbenv"
brew "castiron/bootstrap/phpenv"
brew "nodenv"
brew "yarn", args: ['without-node']
