#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

echo "==> Running cibuild"
echo "==> Darn, we haven't really built this yet for October."
