#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
cd "$(dirname "$0")/.."
if ! brew check-strta-enabled ; then exit 1; fi


PROJ_DIR=$(pwd)
PROJ_NAME=$(basename $PROJ_DIR)

# Bootstrap first
echo "==> Execute ./script/bootstrap"
path="$(dirname "$0")/bootstrap"
$path
echo "==> Bootstrap complete"

if ! [ -f ".env" ]; then
  if [ -f ".env.example" ]; then
    echo "===> Shunting .env into position…"
    cp .env.example .env
  fi
fi

echo "===> Ensuring MySQL is running."
brew services start mysql

db="${PROJ_NAME//-/_}_dev"
if mysql -uroot "${db}" >/dev/null 2>&1 </dev/null
then
  echo "===> Database ${db} exists."
else
  echo "==> Creating database ${db}"
  mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $db";
fi

# Setup the database
php artisan october:up

# Install or update Foreman
if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  echo "==> Installing or updating Foreman gem…"
  gem install foreman
  true
fi

# Ensure DNS and setup nginx
brew setup-ssl $PROJ_NAME "${PROJ_DIR}/config/dev/ssl"
brew setup-nginx-conf $PROJ_NAME $PROJ_DIR config/dev/nginx.conf.erb \
    --extra-val=socket_dir=$PROJ_DIR/tmp/sockets \
    --extra-val=log_dir=$PROJ_DIR/log
exit
