#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

bootstrap="$(dirname "$0")/bootstrap"
$bootstrap

echo "==> Updating db…"
# run all database migrations to ensure everything is up to date.
php artisan october:up
