#!/bin/bash
set -e

echo "==> Checking for Brewfile"

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle --no-upgrade
  }
fi

echo "==> Ensuring a few formula global dependencies…"

# Needed for Nginx check
brew list coreutils >/dev/null 2>&1 || brew install coreutils

# Needed for warewolf
brew list rsync >/dev/null 2>&1 || brew install rsync
