#!/bin/bash
set -e

brew bootstrap-project-all
brew bootstrap-nodenv-node
brew bootstrap-rbenv-ruby
brew bootstrap-phpenv-php

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --without production
  }
fi

if [ -f "package.json" ]; then
  echo "==> Installing node dependencies…"
  yarn install
fi

if [ -f "composer.json" ]; then
  echo "===> Installing PHP dependencies…"
  composer install
fi
