#!/bin/bash
set -e

brew bootstrap-project-all
brew bootstrap-nodenv-node
brew bootstrap-rbenv-ruby

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check >/dev/null 2>&1  || {
    bundle install
  }
fi
