#!/bin/bash
set -e

brew bootstrap-project-all
brew bootstrap-nodenv-node
brew bootstrap-rbenv-ruby
brew bootstrap-phpenv-php

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --without production
  }
fi

if [ -f "package.json" ]; then
  echo "==> Installing node dependencies…"
  yarn install
fi

if ! [ -f "composer.phar" ]; then
  echo "===> Installing composer…"
  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  php composer-setup.php
  php -r "unlink('composer-setup.php');"
fi

if [ -f "composer.json" ]; then
  echo "===> Installing PHP dependencies…"
  php composer.phar install
fi