#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e
if ! brew check-strta-enabled ; then exit 1; fi

# ensure everything in the app is up to date.
update="$(dirname "$0")/update"
$update

echo "===> Ensuring Nginx is running."
brew services start nginx

# boot the app and any other necessary processes.
foreman start
